version: 2
project_name: nats-desktop

archives:
  - strip_binary_directory: true
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - README.md
      - LICENSE
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

builds:
  - id: darwin-amd64
    main: ./cmd/nats-desktop
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-apple-darwin22-clang
      - CXX=x86_64-apple-darwin22-clang++
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X=main.VERSION={{.Tag}}_{{.ShortCommit}}

  - id: darwin-arm64
    main: ./cmd/nats-desktop
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=arm64-apple-darwin22-clang
      - CXX=arm64-apple-darwin22-clang++
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X=main.VERSION={{.Tag}}_{{.ShortCommit}}

  - id: linux-amd64
    main: ./cmd/nats-desktop
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X=main.VERSION={{.Tag}}_{{.ShortCommit}}

  - id: windows-amd64
    main: ./cmd/nats-desktop
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildmode=exe
    ldflags:
      - -s
      - -w
      - -extldflags=-static
      - -X=main.VERSION={{.Tag}}_{{.ShortCommit}}

universal_binaries:
  - ids:
      - darwin-amd64
      - darwin-arm64
    replace: true
    name_template: "{{.ProjectName}}"

checksum:
  name_template: "sha256sums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Version }}-next"
